### ISSUE TITLE
Lower .NET framework targets

### ISSUE THREAD

**Issue by felixSchl** [linerlock/parseq#15]
I see value in being able to run this on platforms lower than 4.0. What is stopping this project from being able to run on e.g. version 3.0 of csharp which introduced extension methods? I am particularly interested in using this project for use in [unity3d](http://unity3d.com/) which is bounded to mono 3.5.

**Comment by linerlock** [comment]
Parseq supports PCL, but since by default PCL only support to .Net Framework 4.0 or later (on VisualStudio 2015 Community). parseq also has become so. (parseq in itself maybe can build on old version of .Net Frameworks)

I don't know well about mono and unity3d so I cannot give appropriate advice to you. I'm sorry.

**Comment by felixSchl** [comment]
Thanks for clarifying. I can only name [UniRx](https://github.com/neuecc/UniRx) which tackles the same problem by simply re-implementing. But if you say the library itself should run fine on 3.5 it would be worth a shot just trying to build it for unity and manage that in it's own repo if the changes are too severe. Given there would be proper accreditation, would you mind this happening?

**Comment by linerlock** [comment]
When you following MIT License, it's no problem.

**Comment by felixSchl** [comment]
Thank you, feel free to close this.
